# Generated by Django 4.2.19 on 2025-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
