# Generated by Django 4.2.20 on 2025-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default="NA", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="cnic_number",
            field=models.CharField(blank=True, default="NA", max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
