# Generated by Django 4.2.20 on 2025-04-30 17:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_address_alter_user_cnic_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="updated_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="feature_vector",
        ),
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Features",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "feature_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_features",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
