# Generated by Django 4.2.20 on 2025-05-09 15:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_updated_at_user_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="admin", max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("officer", "Officer")],
                        default="officer",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="cnic_number",
            field=models.CharField(
                blank=True, default="XXXXXXXXXXXXX", max_length=13, null=True
            ),
        ),
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("query_image", models.TextField()),
                (
                    "matched_user",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
                ("scan_type", models.CharField(max_length=100)),
                ("threshold", models.FloatField()),
                (
                    "scanned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_history",
                        to="users.administrators",
                    ),
                ),
            ],
        ),
    ]
