# Generated by Django 4.2.20 on 2025-05-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_administrators_alter_user_cnic_number_scanhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrators",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="administrators",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="administrators",
            name="session_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="administrators",
            name="session_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
