# Generated by Django 4.2.20 on 2025-05-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrators", "0001_initial"),
        ("users", "0007_administrators_is_active_administrators_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanhistory",
            name="scanned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_history",
                to="administrators.administrators",
            ),
        ),
        migrations.DeleteModel(
            name="Administrators",
        ),
    ]
