# Generated by Django 4.2.2 on 2025-02-17 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.TextField()),
                ('cnic_number', models.CharField(max_length=13, unique=True)),
                ('feature_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
