# Generated by Django 4.2.20 on 2025-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrators",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="admin", max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("officer", "Officer")],
                        default="officer",
                        max_length=10,
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("session_expiry", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
