# Generated by Django 4.2.20 on 2025-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrators",
            name="name",
            field=models.CharField(default="admin", max_length=100, unique=True),
        ),
    ]
