# Generated by Django 4.2.20 on 2025-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrators", "0002_alter_administrators_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrators",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="administrators",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
